// <auto-generated />
using historianalarmservice.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace historianalarmservice.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("historianalarmservice.Model.Alarm", b =>
                {
                    b.Property<int>("alarmId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("alarmColor")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("alarmDescription")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("alarmName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<long?>("datetime")
                        .IsRequired();

                    b.Property<int?>("thingId")
                        .IsRequired();

                    b.HasKey("alarmId");

                    b.ToTable("AlarmCurrents");
                });

            modelBuilder.Entity("historianalarmservice.Model.HistorianAlarm", b =>
                {
                    b.Property<int>("historianId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("alarmColor")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("alarmDescription")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("alarmId");

                    b.Property<string>("alarmName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<long>("endDate");

                    b.Property<long>("startDate");

                    b.Property<int>("thingId");

                    b.HasKey("historianId");

                    b.ToTable("HistorianAlarms");
                });
#pragma warning restore 612, 618
        }
    }
}
